---
- hosts: web
  become: yes
  tasks: 
  -  name: download url packages of jenkins
     get_url:
       url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
       dest: /etc/yum.repos.d/jenkins.repo
  -  name: jenkins key for rpm files
     ansible.builtin.rpm_key:
       state: present
       key: https://pkg.jenkins.io/redhat-stable/jenkins.io.key
  -  name: yum update
     yum:
       name: '*'
       state: latest
  
  -  name: install utilities
     yum: 
       name: "{{  item  }}"
       state: present
     loop:
       -  java
       -  jenkins

  -  name: daemon-reload to pick up config changes
     ansible.builtin.systemd:
       daemon_reload: yes

  -  name: Start jenkins
     ansible.builtin.systemd:
       name: jenkins
       state: started

  -  name: copy initial passwd
     shell: cat /var/lib/jenkins/secrets/initialAdminPassword
     changed_when: false
     register: result
  -  name: print jenkins key
     debug:
       var: result.stdout

